"""Shared API contracts for Meetings AI."""

from .models import DefaultSelection, Meeting, ProviderProfile
from .schemas import (
    AdapterTestResult,
    Capability,
    CapabilityConfig,
    DefaultSelectionRequest,
    DefaultSelectionResponse,
    EmbeddingRequest,
    EmbeddingResult,
    ExecutionLocation,
    FallbackPolicy,
    MeetingCreate,
    MeetingListResponse,
    MeetingPlatform,
    MeetingPublic,
    MeetingStatus,
    MeetingTranscriptResponse,
    MeetingTranscriptSegment,
    ProfileCreate,
    ProfilePublic,
    ProfileUpdate,
    ProviderType,
    TextGenerationRequest,
    TextGenerationResult,
    TranscriptionRequest,
    TranscriptionResult,
    TranscriptionSegment,
)

__all__ = [
    "AdapterTestResult",
    "Capability",
    "CapabilityConfig",
    "DefaultSelection",
    "DefaultSelectionRequest",
    "DefaultSelectionResponse",
    "EmbeddingRequest",
    "EmbeddingResult",
    "ExecutionLocation",
    "FallbackPolicy",
    "Meeting",
    "MeetingCreate",
    "MeetingListResponse",
    "MeetingPlatform",
    "MeetingPublic",
    "MeetingStatus",
    "MeetingTranscriptResponse",
    "MeetingTranscriptSegment",
    "ProfileCreate",
    "ProfilePublic",
    "ProfileUpdate",
    "ProviderProfile",
    "ProviderType",
    "TextGenerationRequest",
    "TextGenerationResult",
    "TranscriptionRequest",
    "TranscriptionResult",
    "TranscriptionSegment",
]
